version: "3"

  api:
    container_name: go-api
    ports:
      - 8000:8000
    build: ./src/backend/
    networks:
        - back
    links: 
      - db
    command: "uvicorn main:app --reload"

volumes:
  db:

networks:
  back:
         
  